
import "./globals.css";
import Root from "./components/Root";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <Root>{children}</Root>;
}
